name 'gce_vault_client'
maintainer 'Cloudreach'
maintainer_email 'oos-vault-chef-client@cloudreach.com'
license 'Apache-2.0'
description 'Installs/Configures vault_client for Google Compute Engine'
long_description 'Installs/Configures vault_client for Google Compute Engine'
source_url 'https://github.com/cloudreach/chef-vault-client'
issues_url 'https://github.com/cloudreach/chef-vault-client/issues'
version '1.0.0'
chef_version '>= 13.0'

supports 'windows'
supports 'centos'
supports 'debian'
supports 'ubuntu'

gem 'vault'
